const admin = require('firebase-admin');
const { onCall, HttpsError } = require('firebase-functions/v2/https');
const { FieldValue } = require('firebase-admin/firestore');
const { COIN_FIELD, calculateSplit, ledgerEntry } = require('./lib/ledger');
const db=()=>admin.firestore(), requests=()=>db().collection('coachingRequests'), users=()=>db().collection('users'), ledger=()=>db().collection('ledger');
function uidOf(r){if(!r.auth?.uid)throw new HttpsError('unauthenticated','Anmeldung erforderlich.');return r.auth.uid;}
function requestIdOf(d){if(typeof d?.requestId!=='string'||!d.requestId.trim())throw new HttpsError('invalid-argument','requestId fehlt.');return d.requestId.trim();}
function assertPositiveInteger(v){const n=Number(v);if(!Number.isSafeInteger(n)||n<=0)throw new HttpsError('failed-precondition','Coin-Betrag muss eine positive Ganzzahl sein.');return n;}
exports.createCoachingRequest=onCall(async r=>{const studentId=uidOf(r),senseiId=typeof r.data?.senseiId==='string'?r.data.senseiId.trim():'';if(!senseiId||senseiId===studentId)throw new HttpsError('invalid-argument','senseiId ist ungueltig.');const priceCoins=assertPositiveInteger(r.data?.priceCoins);const ref=requests().doc();const sensei=await users().doc(senseiId).get();if(!sensei.exists||sensei.get('role')!=='sensei')throw new HttpsError('not-found','Sensei nicht gefunden.');await ref.create({studentId,senseiId,priceCoins,status:'pending',escrowCoins:0,createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});return{ok:true,requestId:ref.id,status:'pending'};});
exports.acceptCoachingRequest=onCall(async r=>{const senseiUid=uidOf(r),id=requestIdOf(r.data),ref=requests().doc(id);await db().runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists)throw new HttpsError('not-found','Anfrage nicht gefunden.');const q=s.data();if(q.senseiId!==senseiUid)throw new HttpsError('permission-denied','Nicht der angefragte Sensei.');if(q.status!=='pending')throw new HttpsError('failed-precondition','Anfrage ist nicht mehr offen.');const price=assertPositiveInteger(q.priceCoins),studentRef=users().doc(q.studentId),student=await tx.get(studentRef);if(!student.exists)throw new HttpsError('not-found','Schueler nicht gefunden.');const balance=Number(student.get(COIN_FIELD)||0);if(!Number.isSafeInteger(balance)||balance<price)throw new HttpsError('failed-precondition','Nicht genug Coins.');tx.update(studentRef,{[COIN_FIELD]:balance-price});tx.update(ref,{status:'accepted',escrowCoins:price,acceptedAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});tx.set(ledger().doc(),ledgerEntry({uid:q.studentId,type:'escrow_hold',amount:-price,referenceId:id}));});return{ok:true,status:'accepted'};});
exports.completeCoachingRequest=onCall(async r=>{const studentUid=uidOf(r),id=requestIdOf(r.data),ref=requests().doc(id);let payout=0,fee=0;await db().runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists)throw new HttpsError('not-found','Anfrage nicht gefunden.');const q=s.data();if(q.studentId!==studentUid)throw new HttpsError('permission-denied','Nur der Schueler kann abschliessen.');if(q.status!=='accepted')throw new HttpsError('failed-precondition','Anfrage ist nicht angenommen.');const split=calculateSplit(q.escrowCoins);fee=split.fee;payout=split.payout;const senseiRef=users().doc(q.senseiId),sensei=await tx.get(senseiRef);if(!sensei.exists)throw new HttpsError('not-found','Sensei nicht gefunden.');const balance=Number(sensei.get(COIN_FIELD)||0);if(!Number.isSafeInteger(balance+payout))throw new HttpsError('failed-precondition','Ungueltiger Kontostand.');tx.update(senseiRef,{[COIN_FIELD]:balance+payout});tx.update(ref,{status:'completed',escrowCoins:0,platformFeeCoins:fee,senseiPayoutCoins:payout,completedAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});tx.set(ledger().doc(),ledgerEntry({uid:q.senseiId,type:'coaching_payout',amount:payout,referenceId:id}));tx.set(ledger().doc(),ledgerEntry({uid:'platform',type:'coaching_fee',amount:fee,referenceId:id}));});return{ok:true,status:'completed',senseiPayoutCoins:payout,platformFeeCoins:fee};});
exports.declineCoachingRequest=onCall(async r=>{const uid=uidOf(r),id=requestIdOf(r.data),ref=requests().doc(id);await db().runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists)throw new HttpsError('not-found','Anfrage nicht gefunden.');const q=s.data();if(q.senseiId!==uid)throw new HttpsError('permission-denied','Nicht der Sensei.');if(q.status!=='pending')throw new HttpsError('failed-precondition','Anfrage ist nicht offen.');tx.update(ref,{status:'declined',updatedAt:FieldValue.serverTimestamp()});});return{ok:true,status:'declined'};});
exports.cancelCoachingRequest=onCall(async r=>{const uid=uidOf(r),id=requestIdOf(r.data),ref=requests().doc(id);await db().runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists)throw new HttpsError('not-found','Anfrage nicht gefunden.');const q=s.data();if(q.studentId!==uid&&q.senseiId!==uid)throw new HttpsError('permission-denied','Nicht beteiligt.');if(q.status!=='accepted')throw new HttpsError('failed-precondition','Nur angenommene Anfragen koennen storniert werden.');const amount=assertPositiveInteger(q.escrowCoins),studentRef=users().doc(q.studentId),student=await tx.get(studentRef);if(!student.exists)throw new HttpsError('not-found','Schueler nicht gefunden.');const balance=Number(student.get(COIN_FIELD)||0);if(!Number.isSafeInteger(balance+amount))throw new HttpsError('failed-precondition','Ungueltiger Kontostand.');tx.update(studentRef,{[COIN_FIELD]:balance+amount});tx.update(ref,{status:'cancelled',escrowCoins:0,refundedCoins:amount,cancelledBy:uid,updatedAt:FieldValue.serverTimestamp()});tx.set(ledger().doc(),ledgerEntry({uid:q.studentId,type:'escrow_refund',amount,referenceId:id}));});return{ok:true,status:'cancelled'};});
